name: A simple demo
on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: write some content to a flile
              run: echo "hello world" > myfile.txt
            - name: sleep for 30 seconds
              run: sleep 10
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: sleep 20
              run: sleep 20
            - name: test presence of file
              run: grep -i "hello" myfile.txt
