name: A simple demo
on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: write some content to a flile
              run: echo "hello world" > myfile.txt
            - name: sleep for 10 seconds
              run: sleep 10
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: myfile
                  path: myfile.txt

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: download artifact
              uses: actions/download-artifact@v5
              with:
                  name: myfile
            - name: test presence of file
              run: grep -i "hello" myfile.txt
