name: Echo every 5 minutes
on: 
    workflow_dispatch

permissions: 
    actions: write
    issues: write
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: logs some values
              run: echo hi